# Generated by Django 3.1.3 on 2022-10-01 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weit',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weit',
            name='user',
            field=models.ForeignKey(help_text='who posts this weit', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发帖人'),
        ),
    ]
