# Generated by Django 3.1.3 on 2022-11-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weits', '0004_weitphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='weit',
            name='comments_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='weit',
            name='likes_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
